package niuhi.elytra.config;

import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.*;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.text.Text;
import niuhi.elytra.ElytraMod;

import static niuhi.elytra.detection.ModEvents.config;

public class YACL {
    public static Screen getConfigScreen(Screen parent) {
        if (!ElytraMod.YACL_LOADED) {
            ElytraMod.LOGGER.info("YACL not loaded");
            return null;
        }

        YetAnotherConfigLib.Builder builder = YetAnotherConfigLib.createBuilder()
                .title(Text.literal("Elytra Revamped Config"))
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("Campfire"))
                        .tooltip(Text.literal("Configure campfire boost mechanics."))
                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("General"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Enabled"))
                                        .description(OptionDescription.of(Text.literal("Enabling or Disabling the boost function of campfires.")))
                                        .binding(true, () -> config.campFire.enabled, val -> config.campFire.enabled = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.literal("Detection Height"))
                                        .description(OptionDescription.of(Text.literal("Change the boost range of campfires WITHOUT hay.")))
                                        .binding(10, () -> config.campFire.detectionHeight, val -> config.campFire.detectionHeight = val)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(5, 25).step(1))
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.literal("Hay Bale Detection Height"))
                                        .description(OptionDescription.of(Text.literal("Change the boost range of campfires WITH hay.")))
                                        .binding(25, () -> config.campFire.hayDetectionHeight, val -> config.campFire.hayDetectionHeight = val)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(10, 50).step(1))
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Text.literal("Base Boost"))
                                        .description(OptionDescription.of(Text.literal("Change the boost amount of campfires WITHOUT hay.")))
                                        .binding(0.3, () -> config.campFire.baseBoost, val -> config.campFire.baseBoost = val)
                                        .controller(opt -> DoubleSliderControllerBuilder.create(opt).range(0.1, 1.0).step(0.05))
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Text.literal("Hay Bale Boost"))
                                        .description(OptionDescription.of(Text.literal("Change the boost amount of campfires WITH hay.")))
                                        .binding(0.5, () -> config.campFire.hayBoost, val -> config.campFire.hayBoost = val)
                                        .controller(opt -> DoubleSliderControllerBuilder.create(opt).range(0.1, 1.5).step(0.05))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Auto-Scale with Height"))
                                        .description(OptionDescription.of(Text.literal("Enabling or Disabling boost scaling with the height detection.")))
                                        .binding(true, () -> config.campFire.autoScaleWithHeight, val -> config.campFire.autoScaleWithHeight = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.literal("Boost Cooldown"))
                                        .description(OptionDescription.of(Text.literal("Cooldown based on Ticks (20 Ticks = 1 Second).")))
                                        .binding(0, () -> config.campFire.boostCooldownTicks, val -> config.campFire.boostCooldownTicks = val)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(5))
                                        .build())
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("Soul Campfire"))
                        .tooltip(Text.literal("Configure soul campfire pull mechanics."))
                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("General"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Enabled"))
                                        .description(OptionDescription.of(Text.literal("Enabling or Disabling the pull function of soul campfires.")))
                                        .binding(true, () -> config.soulFire.enabled, val -> config.soulFire.enabled = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.literal("Detection Height"))
                                        .description(OptionDescription.of(Text.literal("Change the pull range of soul campfires WITHOUT hay.")))
                                        .binding(10, () -> config.soulFire.detectionHeight, val -> config.soulFire.detectionHeight = val)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(5, 25).step(1))
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.literal("Hay Bale Detection Height"))
                                        .description(OptionDescription.of(Text.literal("Change the pull range of soul campfires WITH hay.")))
                                        .binding(25, () -> config.soulFire.hayDetectionHeight, val -> config.soulFire.hayDetectionHeight = val)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(10, 50).step(1))
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Text.literal("Base Pull"))
                                        .description(OptionDescription.of(Text.literal("Change the pull amount of soul campfires WITHOUT hay.")))
                                        .binding(0.3, () -> config.soulFire.basePull, val -> config.soulFire.basePull = val)
                                        .controller(opt -> DoubleSliderControllerBuilder.create(opt).range(0.1, 1.0).step(0.05))
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Text.literal("Hay Bale Pull"))
                                        .description(OptionDescription.of(Text.literal("Change the pull amount of soul campfires WITH hay.")))
                                        .binding(0.5, () -> config.soulFire.hayPull, val -> config.soulFire.hayPull = val)
                                        .controller(opt -> DoubleSliderControllerBuilder.create(opt).range(0.1, 1.5).step(0.05))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Auto-Scale with Height"))
                                        .description(OptionDescription.of(Text.literal("Enabling or Disabling pull scaling with the height detection.")))
                                        .binding(true, () -> config.soulFire.autoScaleWithHeight, val -> config.soulFire.autoScaleWithHeight = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.literal("Pull Cooldown"))
                                        .description(OptionDescription.of(Text.literal("Cooldown based on Ticks (20 Ticks = 1 Second).")))
                                        .binding(0, () -> config.soulFire.pullCooldownTicks, val -> config.soulFire.pullCooldownTicks = val)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(5))
                                        .build())
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("Mechanics"))
                        .tooltip(Text.literal("General Elytra mechanics."))
                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("General"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Disable Fireworks"))
                                        .description(OptionDescription.of(Text.literal("Disabling or Enabling the normale use of Firework Rockets")))
                                        .binding(true, () -> config.mechanics.disableFireworks, val -> config.mechanics.disableFireworks = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Enable Firework Smoke Trails"))
                                        .description(OptionDescription.of(Text.literal("Disabling or Enabling the Smoke Trails when using Fireworks in flight.")))
                                        .binding(true, () -> config.mechanics.enableFireworkSmoke, val -> config.mechanics.enableFireworkSmoke = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Text.literal("Min Horizontal Velocity"))
                                        .description(OptionDescription.of(Text.literal("something with flight detection idk anymore????")))
                                        .binding(0.1, () -> config.mechanics.minHorizontalVelocity, val -> config.mechanics.minHorizontalVelocity = val)
                                        .controller(opt -> DoubleSliderControllerBuilder.create(opt).range(0.0, 0.5).step(0.01))
                                        .build())
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("Feedback"))
                        .tooltip(Text.literal("Visual and audio feedback settings."))
                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("General"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Enable Particles"))
                                        .description(OptionDescription.of(Text.literal("Enabling or Disabling ALL particles made by the Mod.")))
                                        .binding(true, () -> config.feedback.enableParticles, val -> config.feedback.enableParticles = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Enable Sounds"))
                                        .description(OptionDescription.of(Text.literal("Enable or Disable Audible cues for Mod Events.")))
                                        .binding(true, () -> config.feedback.enableSounds, val -> config.feedback.enableSounds = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Sound Volume"))
                                        .description(OptionDescription.of(Text.literal("Extra volume options.")))
                                        .binding(0.5f, () -> config.feedback.soundVolume, val -> config.feedback.soundVolume = val)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.0f, 1.0f).step(0.05f))
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.literal("Sound Pitch"))
                                        .description(OptionDescription.of(Text.literal("Extra sound options, idk why....")))
                                        .binding(1.0f, () -> config.feedback.soundPitch, val -> config.feedback.soundPitch = val)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.5f, 2.0f).step(0.05f))
                                        .build())
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Text.literal("Drag"))
                        .tooltip(Text.literal("Configure drag mechanics."))
                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("General"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Enabled"))
                                        .description(OptionDescription.of(Text.literal("Enable or Disable the Drag feature.")))
                                        .binding(true, () -> config.drag.enabled, val -> config.drag.enabled = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Text.literal("Drag Factor"))
                                        .description(OptionDescription.of(Text.literal("The amount of drag you create.")))
                                        .binding(0.92, () -> config.drag.dragFactor, val -> config.drag.dragFactor = val)
                                        .controller(opt -> DoubleSliderControllerBuilder.create(opt).range(0.5, 1.0).step(0.01))
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.literal("Require Sneaking"))
                                        .description(OptionDescription.of(Text.literal("idk, press shift to use Drag.... Cant remember why this is a thing....")))
                                        .binding(true, () -> config.drag.requireSneaking, val -> config.drag.requireSneaking = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        .build())
                .save(ModConfig::save);
        return builder.build().generateScreen(parent);
    }
}